# Generated by Django 2.2.6 on 2020-03-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='activity_type2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
