# Generated by Django 2.2.6 on 2020-03-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0004_auto_20200328_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
