# Generated by Django 2.2.6 on 2020-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0005_auto_20200328_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
