# Generated by Django 2.2.6 on 2020-03-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0006_auto_20200328_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='gallery'),
        ),
    ]
