# Generated by Django 2.2.6 on 2020-03-29 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0008_auto_20200328_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
