# Generated by Django 2.2.6 on 2020-03-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0009_remove_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(default='gallery/default.jpeg', upload_to='gallery'),
        ),
    ]
