# Generated by Django 2.2.6 on 2020-03-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0010_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
