# Generated by Django 2.2.6 on 2020-03-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homely', '0012_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='activity_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
